In [70]:
for i in arr2:
  print(i)

10
20
30
40
50


In [71]:
x = np.where(arr2 == 20)
print(x)

(array([1]),)


In [72]:
x = np.where(arr2 == 50)
print(x)

(array([4]),)


In [73]:
x = np.where(arrr == 2)
print(x)

(array([1, 4, 7]),)


In [74]:
arraysort = np.array([2,1,5,3,7,5,9,8,5,7,3])

In [75]:
np.sort(arraysort)

array([1, 2, 3, 3, 5, 5, 5, 7, 7, 8, 9])

In [76]:
np.insert(arr2,5,60)

array([10, 20, 30, 40, 50, 60])

In [77]:
np.insert(arraysort,11,10)

array([ 2,  1,  5,  3,  7,  5,  9,  8,  5,  7,  3, 10])

In [78]:
np.insert(arraysort,0,100)

array([100,   2,   1,   5,   3,   7,   5,   9,   8,   5,   7,   3])

In [79]:
np.delete(arraysort,0)

array([1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

In [80]:
arraysort

array([2, 1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

In [81]:
arrr1 = np.insert(arr2,5,60)

In [82]:
arrr1

array([10, 20, 30, 40, 50, 60])

In [83]:
arr2

array([10, 20, 30, 40, 50])

In [84]:
index = [0,1,2]

In [85]:
arrr2 = np.delete(arr2,index)

In [86]:
arrr2

array([40, 50])

In [87]:
arr2

array([10, 20, 30, 40, 50])

In [88]:
np.flip(arr2)

array([50, 40, 30, 20, 10])

In [89]:
arr2

array([10, 20, 30, 40, 50])

In [90]:
arrflip = np.flip(arr2)

In [91]:
arrflip

array([50, 40, 30, 20, 10])

In [92]:
arr2[0] = 100

In [93]:
arr2

array([100,  20,  30,  40,  50])

In [94]:
arr2.sort()

In [95]:
arr2

array([ 20,  30,  40,  50, 100])

In [96]:
np.append(arr2,1000)

array([  20,   30,   40,   50,  100, 1000])

In [97]:
arr2

array([ 20,  30,  40,  50, 100])

In [113]:
arr2.append(1000)

AttributeError: 'numpy.ndarray' object has no attribute 'append'